### ISSUE TITLE
Fix Alignment of Create Message Window forms.

### ISSUE THREAD

**Issue by umin18** [YongCho/MinimalEmailClient#28]
Forms on CreateMessageWindow.xaml are misaligned when viewed from smaller resolution displays.

**Comment by umin18** [comment]
Requires Testing - 5cc390598940b601afeb556e2e550a92eb7fb7c0

**Comment by YongCho** [comment]
I just tested this on my laptop and the issue is present. Please see the attached screenshot.
<img src="https://www.dropbox.com/s/z4jc95orgptnccs/createMsgView.PNG?raw=1" />

A better way to align the controls in this case is to place all misaligned controls in a grid instead of two different stackpanels.

**Comment by umin18** [comment]
Using a Grid in this situation will only provide boundaries between the ToolBarPanel and the message TextBox but won't fix the issue of alignment between the buttons and the header textboxes.  Button heights do not align when with textbox heights when using the same value.

**Comment by YongCho** [comment]
I will work on this issue since you don't have a means to test it.
